language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2.1-003177
mono:
  - latest
os:
  - linux
node_js:
- '6.10.1'
before_install:
- npm install -g json-diff fs path child_process
- npm install -g eslint coffeelint csslint jshint standard htmlhint jslint
install:
- sh script/setup.sh
- sh script/cibuild.sh
script:
- node test/integration.js